spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: stockpricebackend

kis:
  url: ${WS_URL}
  real_port: ${REAL_PORT}
  test_port: ${TEST_PORT}
  stockNames: ${STOCK_NAMES}
  stockCodes: ${STOCK_CODES}
  trIdNames: ${TRID_NAMES}
  trIds: ${TRIDS}
  blue:
    appkey: ${BLUE_APPKEY}
    appsecret: ${BLUE_APPSECRET}
    personalsecKey: ${BLUE_PERSONALSECKEY}
    custType: ${BLUE_CUSTTYPE}
    contentType: ${BLUE_CONTENTTYPE}
    htsId: ${BLUE_HTSID}
  green:
    appkey: ${GREEN_APPKEY}
    appsecret: ${GREEN_APPSECRET}
    personalsecKey: ${GREEN_PERSONALSECKEY}
    custType: ${GREEN_CUSTTYPE}
    contentType: ${GREEN_CONTENTTYPE}
    htsId: ${GREEN_HTSID}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}